### ISSUE TITLE
[Chapter 8] Tracking Known Bugs

### ISSUE THREAD

**Issue by dkmonaghan** [sem5640-2018/docs#46]
Please list known bugs here with a brief description of the issue and the microservice it affects. 

*Health Dashboard* :
- If an activity type is not defined at all the page will fail to load
- Rankings: user can only see rankings within their group, not ranking of their group within all groups. 
- User cannot select timeframe to show data from.
- Only number of steps is visualised from the activity metrics (not Average Heart Rate, Calories Burnt etc)

**Comment by arglanc** [comment]
Gatekeeper:

- Administrator can change their own user type to something other than administrator, leaving the system with no administrator.

**Comment by DavidFair** [comment]
*Challenges*
- Editing a challenge doesn't, however this is not a FR

**Comment by AGEdwards** [comment]
*Booking & Facilities*
- Venue deletion "are you sure?" doesn't specifically mention about also deleting associated facilities

**Comment by AGEdwards** [comment]
*Other*
- We should probably mention about the lack of localisation ability. Probably that we just didn't think about it until it was too big a job to add.

**Comment by JackThomson2** [comment]
_Ladders_

- The created ladder is not tied to a sport rather the name is manually typed

**Comment by JackThomson2** [comment]
_Ladders_

- When not cleanly removed from a ladder when they remove themselves i.e. joining another ladder

**Comment by ckl2** [comment]
_Dashboard_ 

- Rankings: user can only see rankings within their group, not ranking of their group within all groups.

**Comment by RobertMouncer** [comment]
_Booking Facilities_

- As an admin on the Index page, all bookings are shown to be made by "unknown user". This was working previously but since implementing the "unknown user" functionality, the user is only visible from the booking's delete page.

**Comment by RobertMouncer** [comment]
_Challenges_

- Email updates aren't working.

**Comment by dkmonaghan** [comment]
These are all now in Chapter 7. If you have more to add, please contact me directly.
